In [55]:
from Run_Pipeline.Agent_Tool import AgentTools
from Run_Pipeline.Document_Loader import DocumentLoader
from Run_Pipeline.Document_Splitter import DocumentSplitter
from Run_Pipeline.Embedding_DB import EmbeddingDB
from Run_Pipeline.Env_Loader import (EnvLoader)
from Run_Pipeline.LLM_Factory import LLMFactory
from Run_Pipeline.Retriever_Builder import RetrieverBuilder
from pathlib import Path
import os

EnvLoader.load_local(dotenv_path="../.env")

BASE_DIR = Path(os.getcwd()).parent

kind = "json"
file_path = BASE_DIR / os.getenv("DATA_PATH")
chunk_size = 512
overlap_size = 50
device = "mps"
persist_dir = BASE_DIR / os.getenv("DATA_PATH") / f"{kind}_{chunk_size}"
retriever_mode = 3
k = 3
engine_num = 1
backend_num = 1

In [56]:
def build_chain():
    """
    RAG 파이프라인을 초기화해 LangSmith가 매 예제마다 새로 씁니다.
    """
    # --- ☑️ 당신이 앞서 작성한 코드 재사용 ---
    loader = DocumentLoader(file_path, kind)
    docs_post, docs_company = loader._load_json_files()

    splitter = DocumentSplitter(chunk_size=512, overlap=50)
    chunks = splitter.split(docs_post + docs_company, cache_dir=file_path)

    embed_db = EmbeddingDB(
        model_name="nlpai-lab/KURE-v1",
        device="mps",
        persist_dir=persist_dir
    )
    db = embed_db.get_or_create_db(chunks)

    retriever = RetrieverBuilder(
        db=db,
        full_docs=docs_post + docs_company,
        chunks=chunks,
        k=3,
    ).build(mode = retriever_mode)

    llm = LLMFactory.load_llm(engine=1, backend=1, device="mps")

    from Run_Pipeline.Chain_Factory import ChainFactory
    return ChainFactory.build_chain(retriever=retriever, llm=llm)

In [57]:
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from Run_Pipeline.LLM_Factory import LLMFactory
# from Run_Pipeline.Retriever_Builder import RetrieverBuilder
# from Run_Pipeline.Embedding_DB import EmbeddingDB
# from Run_Pipeline.Document_Splitter import DocumentSplitter
# from Run_Pipeline.Document_Loader import DocumentLoader
#
#
# def _len_okt(self, text: str) -> int:
#     return len(self.okt.morphs(text))
#
#
# def _okt_tokenize(self, text: str):
#     return self.okt.morphs(text)
#
#
# def build_chain():
#     """
#     RAG 파이프라인을 초기화해 LangSmith가 매 예제마다 새로 씁니다.
#     """
#     # --- ☑️ 당신이 앞서 작성한 코드 재사용 ---
#     loader = DocumentLoader(file_path, kind)
#     docs_post, docs_company = loader._load_json_files_simple()
#
#     splitter = DocumentSplitter(chunk_size=chunk_size, overlap=overlap_size)  # 이미 분할된 문서가 있다면 로드하고 아니면 새로 스플릿함
#     chunks = splitter.split_simple(docs_post + docs_company, cache_dir=file_path)  # 게시글과 회사 정보를 합쳐서 분할
#
#
#     embed_db = EmbeddingDB(
#         model_name="nlpai-lab/KURE-v1",
#         device="mps",
#         persist_dir=persist_dir
#     )
#     db = embed_db.get_or_create_db_simple(chunks)
#
#     retriever = RetrieverBuilder(
#         db=db,
#         full_docs=docs_post + docs_company,
#         chunks=chunks,
#         k=3,
#     ).build(mode=retriever_mode)
#
#     llm = LLMFactory.load_llm(engine=1, backend=1, device="mps")
#
#     from Run_Pipeline.Chain_Factory import ChainFactory
#     return ChainFactory.build_chain(retriever=retriever, llm=llm)

In [ ]:
chain = build_chain()

In [58]:
import pandas as pd

df = pd.read_excel('../Data_Files/RAG_test_questions.xlsx')
my_questions = df['Question'].to_list()

In [60]:
# rag_to_langsmith.py
"""질문 리스트를 RAG 체인에 통과시켜 (질문, 답변, 맥락)을 LangSmith 데이터셋에 업로드하는 스크립트.

사용법 예시:

    from your_build_module import build_chain  # 기존 build_chain 가져오기
    from rag_to_langsmith import upload_qac_dataset

    questions = [
        "회사의 핵심 사업은 무엇인가요?",
        "재택근무 제도는 있나요?",
        # ...
    ]

    upload_qac_dataset(build_chain, questions, dataset_name="rag_qac_dataset")
"""

from __future__ import annotations

import json
from typing import Callable, Dict, List, Any

from langsmith import Client
from langchain.schema import Document


###############################################################################
# LangSmith 업로드 유틸
###############################################################################

def _upload_to_langsmith(records: List[Dict[str, str]], dataset_name: str) -> str:
    """records = [{question, answer, context}, ...] 형태를 LangSmith에 업로드."""
    client = Client()

    # 기존 동일 이름 데이터셋이 있으면 삭제
    for ds in client.list_datasets():
        if ds.name == dataset_name:
            client.delete_dataset(dataset_id=ds.id)
            break

    dataset = client.create_dataset(dataset_name=dataset_name)

    for idx, r in enumerate(records, 1):
        client.create_example(
            dataset_id=dataset.id,
            inputs={"question": r["question"]},
            outputs={
                "answer": r["answer"],
                "context": r["context"],
            },
            metadata={"row": idx},
        )

    print(f"[LangSmith] '{dataset_name}' 업로드 완료! (총 {len(records)}개)")
    return dataset_name


###############################################################################
# RAG 체인 실행 결과에서 answer / context 추출 유틸
###############################################################################


def _extract_answer(result: Any) -> str:
    """체인 invoke 결과에서 답변 문자열 추출."""
    if isinstance(result, str):
        return result
    if isinstance(result, dict):
        # 수정된 ChainFactory의 결과 구조
        if "answer" in result:
            return str(result["answer"])
        # 기존 구조들
        for key in ("result", "output"):
            if key in result:
                return str(result[key])
    # LangChain Runnable 시나리오: LLMResult list 등
    return str(result)


def _extract_context(result: Any) -> str:
    """체인 invoke 결과에서 맥락(source_documents) 텍스트 추출."""
    # 수정된 ChainFactory의 결과 구조
    if isinstance(result, dict):
        if "context" in result:
            return str(result["context"])
        if "source_documents" in result:
            docs = result["source_documents"]
            if hasattr(docs, '__iter__'):
                return "\n\n".join(getattr(doc, 'page_content', str(doc)) for doc in docs)

    # 1) attr 로 존재할 때
    if hasattr(result, "source_documents"):
        docs = getattr(result, "source_documents")
        return "\n\n".join(doc.page_content for doc in docs)

    # 2) dict 구조 - 기존
    if isinstance(result, dict):
        if "retrieved_docs" in result:
            return "\n\n".join(str(d) for d in result["retrieved_docs"])

    return "(맥락 추출 불가)"


###############################################################################
# 디버깅 유틸리티
###############################################################################

def debug_chain_input(build_chain_fn: Callable[[], Any]) -> None:
    """체인의 입력 스키마를 확인하는 디버깅 함수"""
    chain = build_chain_fn()
    print("=" * 50)
    print("Chain Debug Information")
    print("=" * 50)
    print(f"Chain type: {type(chain)}")

    # 입력 스키마 확인
    try:
        if hasattr(chain, 'input_schema'):
            schema = chain.input_schema.schema()
            print(f"Input schema: {schema}")
            if 'properties' in schema:
                print(f"Expected input keys: {list(schema['properties'].keys())}")
    except Exception as e:
        print(f"Cannot get input schema: {e}")

    # 체인 구조 확인
    if hasattr(chain, 'steps'):
        print(f"Chain steps: {[type(step).__name__ for step in chain.steps]}")

    print("=" * 50)


###############################################################################
# 메인 함수
###############################################################################


def upload_qac_dataset(
        build_chain_fn: Callable[[], Any],
        questions: List[str],
        dataset_name: str = "rag_qac_dataset",
        show_progress: bool = True,
) -> str:
    """build_chain 함수와 질문 리스트를 받아 LangSmith 데이터셋 생성.

    Args:
        build_chain_fn: 빌드된 Chain 을 반환하는 콜러블 (ex. build_chain)
        questions: 문자열 질문 리스트
        dataset_name: LangSmith 상에 생성할 데이터셋 이름
        show_progress: True면 진행 상황 print
    Returns:
        dataset_name (str)
    """
    chain = build_chain_fn()
    records: List[Dict[str, str]] = []
    for idx, q in enumerate(questions, 1):
        if show_progress:
            print(f"[{idx}/{len(questions)}] Q: {q[:30]}…", end=" ")
        try:
            # ChainFactory.build_chain은 "input" 키를 기대함
            result = chain.invoke({"input": q})
            answer = _extract_answer(result)
            context = _extract_context(result)

        except Exception as e:
            answer = f"오류 발생: {e}"
            context = ""
        records.append({"question": q, "answer": answer, "context": context})
        if show_progress:
            print("✅")

    return _upload_to_langsmith(records, dataset_name)

In [61]:
if __name__ == "__main__":

    # 데이터셋 업로드 실행
    upload_qac_dataset(
        build_chain,
        my_questions,
        dataset_name="rag_qac_dataset_Retriever_3",  # ↔︎ 실제 이름
        show_progress=True
    )

캐시에서 62865개의 문서 청크 로드 완료
▶ 기존 Chroma DB 로드 중...
▶ 로드 완료
▶ BM25 색인 중…

BM25 문서 인덱싱: 100%|██████████| 62865/62865 [00:00<00:00, 1377712.69doc/s]

[1/30] Q: 컬리 ‘프로모션 기획 마케터’ 포지션의 최소 필요 경력… 컬리의 '프로모션 기획 마케터' 포지션에 대한 정보는 제공되지 않았습니다. 그러나, 마케팅 관련 직무에서 일반적으로 요구되는 최소 경력은 5년 이상인 경우가 많습니다. 정확한 경력 요건은 컬리의 공식 채용 공고를 확인하시거나 인사팀에 문의하시는 것이 좋습니다.✅
[2/30] Q: 씨제이올리브영 ‘커머스디자이너’ 포지션 지원 시 필수로… 씨제이올리브영의 '커머스디자이너' 포지션에 지원할 때 필수로 제출해야 하는 것은 다음과 같습니다:

1. 이력서
2. 포트폴리오

이력서에는 희망 연봉을 반드시 기재해야 하며, 포트폴리오는 지원자의 디자인 역량을 보여줄 수 있는 중요한 자료입니다. 서류 제출 시 파일 크기가 50MB를 넘는 경우에는 링크를 첨부하여 제출해야 합니다.✅
[3/30] Q: 111퍼센트 ‘웹 프론트 개발자’ 포지션에서 주 사용 … 111퍼센트의 '웹 프론트 개발자' 포지션에서 주 사용 프레임워크는 React입니다. 이 포지션에서는 React와 TypeScript를 이용해 신규 어플리케이션을 개발하고, 사내 인하우스 툴의 프론트엔드 신규 개발 및 유지보수를 담당하게 됩니다.✅
[4/30] Q: 토스페이먼츠 ‘Frontend Developer’ 포지… 토스페이먼츠의 'Frontend Developer' 포지션에서 사용하는 상태 관리 라이브러리는 Riverpod, BLoC, Provider입니다. 이 라이브러리들은 Flutter 애플리케이션에서 상태 관리를 효율적으로 수행하는 데 도움을 줍니다.✅
[5/30] Q: 미리디 ‘미리캔버스 프론트엔드팀’이 모노레포 구현을 위… 미리디 '미리캔버스 프론트엔드팀'이 모노레포 구현을 위해 도입한 도구는 **Turborepo**입니다. Turborepo를 활용하여 멀티 패키지 관리 및 빌드 속도를 최적화하고, CICD 환경에서도 효율적인 모듈 배포를 가능하게 하여 개발 및 배포 속도를 극대화하고 있습니다.✅
[6/30] Q: 여기어때 ‘Product Owner 파트너서비스’ 포지… 여기어때의 'Product Owner 파트너서비스' 포지션에서 월요일 공식 출근 시간은 오후 1시입니다. 이는 여유 있는 한 주의 시작을 위해 설정된 시간입니다.✅
[7/30] Q: 타다 ‘프로덕트 디자이너’ 서류 제출 예시에서 ‘김타다… 타다의 '프로덕트 디자이너' 서류 제출 예시에서 '김타다이력서'와 짝을 이루는 포트폴리오 파일명 예시는 '김타다포트폴리오'입니다. 모든 서류의 파일명은 이름과 제출서류 형식으로 통일해야 하므로, 이와 같은 형식으로 제출하시면 됩니다.✅
[8/30] Q: 페이타랩 ‘패스오더 프론트엔드 개발자’가 주로 사용하는… 페이타랩의 '패스오더 프론트엔드 개발자'가 주로 사용하는 두 가지 기본 프로그래밍 언어는 **JavaScript**와 **TypeScript**입니다. 이 언어들은 웹 개발에서 널리 사용되며, 특히 React와 같은 프레임워크와 함께 사용되어 사용자 경험을 향상시키는 데 중요한 역할을 합니다.✅
[9/30] Q: 강남언니 ‘프로덕트 디자이너 주니어’ 포지션의 기본 출… 강남언니 '프로덕트 디자이너 주니어' 포지션의 기본 출근 기준 시간은 오전 9시부터 오전 11시까지 자율 출근입니다.✅
[10/30] Q: 씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’… 씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’ 포지션에서 요구되는 주요 디자인 툴 두 가지는 Figma와 Adobe입니다. 이 툴들은 UI 디자인 및 UX 설계에 필수적인 도구로, 디자인 시스템 구축 및 관리에 활용됩니다.✅
[11/30] Q: 컬리 ‘프로모션 기획 마케터’는 성과 분석 시 어떤 두… 컬리의 '프로모션 기획 마케터' 포지션에서 성과 분석 시 관리해야 하는 두 가지 핵심 지표는 '유입'과 '전환'입니다. 이 지표들은 이커머스 업계에서 마케팅 및 프로모션의 효과를 평가하는 데 중요한 역할을 하며, 고객의 구매 행동을 이해하고 최적화하는 데 필수적입니다.✅
[12/30] Q: 111퍼센트 ‘웹 프론트 개발자’ 우대 사항으로 언급된… 111퍼센트의 '웹 프론트 개발자' 포지션에서 우대 사항으로 언급된 세 가지 경험 유형은 다음과 같습니다:

1. **기술적 난관 앞에서 해결책을 찾아가는 과정**을 즐기는 경험.
2. **동료들과의 적극적인 소통을 통해 아이디어를 공유하고 문제를 해결하는 경험**.
3. **새로운 지식 습득에 대한 열정과 긍정적인 기술적 영향력을 전파하고 싶은 경험**.

이러한 경험들은 팀워크와 문제 해결 능력을 강조하며, 개발자로서의 성장과 협업을 중요시하는 111퍼센트의 가치와 잘 맞아떨어집니다.✅
[13/30] Q: 토스페이먼츠 Frontend Developer 포지션에… 토스페이먼츠의 Frontend Developer 포지션에서 챕터가 주기적으로 진행하는 두 가지 기술 공유 활동은 '챕터 위클리'와 'LightningTalk'입니다. 챕터 위클리는 팀원들이 모여서 진행하는 정기적인 회의이며, LightningTalk은 새로운 기술 토픽이나 개발 노하우를 공유하는 세션입니다. 이러한 활동을 통해 팀원들은 서로의 지식을 나누고, 자연스럽게 성장할 수 있는 기회를 갖게 됩니다.✅
[14/30] Q: 미리디 ‘미리캔버스 프론트엔드팀’이 글로벌 성능 최적화… 미리디의 미리캔버스 프론트엔드팀이 글로벌 성능 최적화를 위해 도입한 렌더링 기법은 **서버사이드 렌더링(SSR)**입니다. 이 기법의 목적은 전 세계 어디서든 사용자들이 쾌적하게 에디터를 사용할 수 있도록 최적화하는 것입니다.

서버사이드 렌더링을 통해 초기 페이지 로딩 속도를 개선하고, 사용자 경험을 향상시키며, 검색 엔진 최적화(SEO)에도 긍정적인 영향을 미칠 수 있습니다. 이를 통해 미리캔버스는 다양한 디바이스와 환경에서도 최적의 사용자 경험을 제공할 수 있도록 하고 있습니다.✅
[15/30] Q: 여기어때 ‘Product Owner 파트너서비스’ 포지… 여기어때 ‘Product Owner 파트너서비스’ 포지션에서 파트너 행동 데이터를 활용해 우선순위를 관리하는 대상은 주로 파트너 플랫폼의 개선 사항과 운영 효율성입니다. 구체적으로는 다음과 같은 요소들이 포함될 수 있습니다:

1. **파트너 어드민 개선**: 파트너가 사용하는 관리 시스템의 기능이나 사용자 경험을 개선하기 위한 우선순위 설정.
2. **내부 운영 어드민 개선**: 내부 운영자들이 사용하는 시스템의 효율성을 높이기 위한 개선 사항.
3. **문제 정의 및 해결**: 파트너 행동 데이터와 VOC(Voice of Customer)를 분석하여 파트너가 겪고 있는 문제를 정의하고, 이를 해결하기 위한 프로젝트의 우선순위 설정.
4. **백로그 관리**: 파트너의 요구사항과 피드백을 바탕으로 개선할 사항들을 정리하고, 이를 우선순위에 따라 관리하는 작업.

이러한 데이터 기반의 접근 방식은 파트너와 내부 운영자 모두의 사용성을 높이고, 비즈니스 임팩트를 극대화하는 데 중요한 역할을 합니다.✅
[16/30] Q: 타다 ‘프로덕트 디자이너’의 문제 해결 프로세스에서 첫… 타다의 프로덕트 디자이너가 문제 해결 프로세스에서 첫 번째로 설정하고 발굴해야 하는 것은 '문제'입니다. 이는 사용자의 필요와 불편함을 이해하고, 이를 바탕으로 가설을 설정하는 과정으로 이어집니다. 문제를 명확히 정의하는 것이 이후 솔루션을 제시하고, 제품의 기능을 설계하는 데 있어 매우 중요한 기초가 됩니다. 따라서, 초기 단계에서 문제를 발굴하고 이를 명확히 설정하는 것이 성공적인 제품 개발의 출발점이라고 할 수 있습니다.✅
[17/30] Q: 페이타랩 ‘패스오더’ 프로덕트팀이 지양한다고 밝힌 업무… 페이타랩 '패스오더' 프로덕트팀이 지양하는 업무 프로세스는 불필요하고 복잡한 요소를 배제하고, 실행 중심의 효율적인 업무 문화를 갖추는 것입니다. 이는 팀이 고객지향적인 프로덕트를 개발하기 위해 유기적인 의사소통을 통해 다양한 아이디어와 프로젝트를 흡수하고 구현하는 데 중점을 두고 있다는 것을 의미합니다. 이러한 접근은 팀원들이 안정적이면서도 혁신적인 프로덕트를 개발하기 위해 필요한 학습과 실행을 적극적으로 수행할 수 있도록 돕습니다. 결과적으로, 팀은 효율성을 높이고, 빠른 실행력을 통해 비즈니스 임팩트를 극대화하는 것을 목표로 하고 있습니다.✅
[18/30] Q: 강남언니 ‘프로덕트 디자이너 주니어’가 데이터 기반 의… 강남언니의 '프로덕트 디자이너 주니어'가 데이터 기반 의사결정을 위해 활용할 수 있는 두 가지 UX 리서치 방법은 다음과 같습니다:

1. **사용자 인터뷰(User Interviews)**: 사용자 인터뷰는 고객의 요구와 문제를 깊이 이해하기 위한 정성적 리서치 방법입니다. 이 방법을 통해 사용자의 경험, 기대, 불만 등을 직접적으로 들을 수 있으며, 이를 통해 제품 개선에 필요한 인사이트를 얻을 수 있습니다. 인터뷰를 통해 수집된 데이터는 제품 디자인의 방향성을 설정하는 데 중요한 역할을 합니다.

2. **A/B 테스트(A/B Testing)**: A/B 테스트는 두 가지 이상의 디자인 또는 기능을 사용자에게 동시에 제공하고, 어떤 버전이 더 나은 성과를 내는지를 비교하는 정량적 리서치 방법입니다. 이 방법을 통해 사용자의 행동 데이터를 수집하고, 어떤 디자인이 더 효과적인지를 데이터 기반으로 판단할 수 있습니다. A/B 테스트는 제품의 특정 요소를 개선하는 데 매우 유용하며, 실험 결과를 통해 명확한 의사결정을 내릴 수 있습니다.

이 두 가지 방법은 강남언니의 프로덕트 디자이너 주니어가 사용자 경험을 개선하고, 데이터 기반의 의사결정을 내리는 데 큰 도움이 될 것입니다.✅
[19/30] Q: 씨제이올리브영 ‘커머스디자이너’ 우대 사항에서 ‘디자인… 씨제이올리브영의 '커머스디자이너' 포지션에서 '디자인 시스템 또는 UI 가이드 제작·운영 경험'은 주로 다음과 같은 프로젝트 성격과 연결됩니다.

1. **일관성 있는 사용자 경험 제공**: 디자인 시스템은 브랜드의 비주얼 아이덴티티와 사용자 경험을 일관되게 유지하기 위해 필수적입니다. 커머스 플랫폼에서 다양한 페이지와 요소들이 통일된 디자인 언어를 사용해야 하므로, UI 가이드를 통해 디자이너와 개발자 간의 원활한 협업이 이루어질 수 있습니다.

2. **효율적인 디자인 프로세스**: 디자인 시스템을 구축하면 반복적인 디자인 작업을 줄이고, 새로운 프로젝트나 기능 추가 시 빠르게 적용할 수 있습니다. 이는 시간과 비용을 절감하는 데 기여하며, 더 나은 품질의 결과물을 도출할 수 있습니다.

3. **협업 및 커뮤니케이션 강화**: UI 가이드는 다양한 팀(디자인, 개발, 마케팅 등) 간의 커뮤니케이션을 원활하게 해줍니다. 각 팀이 동일한 기준을 가지고 작업할 수 있도록 도와주어, 프로젝트 진행 시 발생할 수 있는 혼란을 줄여줍니다.

4. **사용자 피드백 반영**: 디자인 시스템은 사용자 피드백을 기반으로 지속적으로 개선될 수 있습니다. 커머스디자이너는 이러한 피드백을 반영하여 UI 가이드를 업데이트하고, 사용자 경험을 향상시키는 데 기여할 수 있습니다.

결론적으로, '디자인 시스템 또는 UI 가이드 제작·운영 경험'은 커머스 플랫폼의 디자인 일관성을 유지하고, 효율적인 작업 흐름을 구축하며, 다양한 팀 간의 협업을 촉진하는 데 중요한 역할을 합니다. 이러한 경험은 올리브영의 비전인 글로벌 No1 옴니채널 라이프스타일 플랫폼으로의 발전에 기여할 수 있습니다.✅
[20/30] Q: 미리디 복지 정책 중 ‘유연근무제도’가 허용하는 시차 … 미리디의 유연근무제도에서는 시차 출퇴근이 오전 8시부터 11시 사이에 가능하다고 합니다. 즉, 직원들은 오전 8시에서 11시 사이에 자율적으로 출근할 수 있습니다.✅
[21/30] Q: 컬리 ‘프로모션 기획 마케터’가 월 단위 주요 프로모션… 컬리의 '프로모션 기획 마케터'가 월 단위 주요 프로모션 테마를 기획할 때 포함해야 하는 두 가지 관점은 다음과 같습니다:

1. **고객의 니즈**: 고객이 어떤 상품이나 혜택에 관심을 가지고 있는지를 파악하고, 이를 바탕으로 고객의 기대에 부합하는 프로모션 테마를 설정해야 합니다. 고객의 구매 패턴, 선호도, 계절적 요인 등을 분석하여 고객이 실제로 원하는 프로모션을 기획하는 것이 중요합니다.

2. **상품의 특성**: 프로모션에 포함될 상품의 특성과 장점을 고려해야 합니다. 상품의 시즌성, 인기 상품, 신규 출시 상품 등을 반영하여 매력적인 프로모션 테마를 설정함으로써 고객의 관심을 끌고 구매를 유도할 수 있습니다.

이러한 활동은 **사업 목표 달성을 위한 온사이트 프로모션 전략** 내에서 수행됩니다. 즉, 고객의 즐거운 장보기 경험을 제공하고, 이를 통해 고객의 구매를 촉진하는 것이 궁극적인 목표입니다. 프로모션 기획 마케터는 이러한 전략을 바탕으로 고객의 니즈와 상품 특성을 반영한 프로모션 테마를 기획하여 팀의 목표 달성에 기여하게 됩니다.✅
[22/30] Q: 111퍼센트 ‘웹 프론트 개발자’ 공고에 따르면 사옥은… 111퍼센트는 2025년 8월경 성수동으로 사옥을 확장 이전할 예정입니다. 지원자는 이 정보를 지원 시 참조하라는 안내가 있습니다. 즉, 지원자는 자신의 지원서나 면접에서 이 정보를 활용하여 회사의 미래 계획에 대한 관심과 이해도를 보여줄 수 있습니다. 이는 지원자가 회사에 대한 진지한 관심을 가지고 있음을 나타내는 좋은 기회가 될 것입니다.✅
[23/30] Q: 토스페이먼츠 Frontend Developer 포지션에… 토스페이먼츠의 Frontend Developer 포지션에서 '결제 위젯'과 '대시보드 고도화'가 공통으로 해결하려는 결제 도메인의 두 가지 핵심 요구 특성은 다음과 같습니다.

1. **직관성과 사용자 경험**: 결제 위젯은 소비자들이 쉽게 결제를 진행할 수 있도록 직관적이고 사용하기 쉬운 인터페이스를 제공해야 합니다. 이는 결제 과정에서의 사용자 경험을 극대화하여 소비자들이 불편함 없이 결제를 완료할 수 있도록 하는 것이 중요합니다. 대시보드 또한 가맹점들이 복잡한 결제 및 정산 과정을 쉽게 관리할 수 있도록 직관적인 UI/UX를 제공해야 합니다.

2. **확장성과 유연성**: 결제 도메인은 다양한 요구사항과 복잡한 정책을 포함하고 있습니다. 결제 위젯은 이러한 다양한 요구를 충족할 수 있도록 설계되어야 하며, 새로운 기능이나 요구사항이 추가될 때 유연하게 대응할 수 있어야 합니다. 대시보드 고도화 역시 가맹점의 다양한 관리 요구를 수용할 수 있도록 확장 가능하고 유연한 아키텍처를 갖추어야 합니다.

이 두 가지 특성은 결제 서비스의 효율성과 사용자 만족도를 높이는 데 필수적이며, 토스페이먼츠가 목표로 하는 혁신적인 결제 경험을 제공하는 데 중요한 역할을 합니다.✅
[24/30] Q: 미리디 ‘미리캔버스 프론트엔드팀’이 Micro Fron… 미리디의 미리캔버스 프론트엔드팀이 Micro Frontends 아키텍처 구현에 활용한 Webpack 5의 주요 기능은 **모듈 페더레이션(Module Federation)**입니다. 이 기능은 독립적인 애플리케이션들이 하나의 서비스처럼 동작할 수 있도록 설계되어, 각 Micro App 간의 의존성을 분리하고 개별 배포 파이프라인을 구축하는 데 기여합니다.

이를 통해 달성하려는 두 가지 시스템적 목표는 다음과 같습니다:

1. **확장성**: Micro Frontends 아키텍처를 통해 각 애플리케이션이 독립적으로 개발 및 배포될 수 있어, 서비스의 확장성과 유지보수성을 높입니다. 이는 빠르게 변화하는 서비스 환경에 적응할 수 있는 유연성을 제공합니다.

2. **개발 생산성 향상**: 개별 배포 파이프라인을 통해 팀 간의 협업이 원활해지고, 개발 및 배포 속도를 극대화할 수 있습니다. 이는 팀 개발 문화와 코드 품질 향상에도 긍정적인 영향을 미칩니다.

이러한 목표들은 미리캔버스의 서비스 품질을 높이고, 사용자 경험을 개선하는 데 중요한 역할을 합니다.✅
[25/30] Q: 여기어때 ‘Product Owner 파트너서비스’ 복지… 여기어때 ‘Product Owner 파트너서비스’의 복지 항목 중 연간 100만 포인트와 100만원 쿠폰팩은 각각 다음과 같은 용도로 사용될 수 있습니다.

1. **연간 100만 포인트**: 이 포인트는 직원 개인이 사용할 수 있는 포인트로, 여기어때의 다양한 서비스나 상품에 활용할 수 있습니다. 직원의 복지 향상과 개인적인 혜택을 위해 제공됩니다.

2. **100만원 쿠폰팩**: 이 쿠폰팩은 직원 본인과 그 지인들이 사용할 수 있도록 제공됩니다. 즉, 직원이 자신의 지인과 함께 쿠폰을 활용하여 여기어때의 서비스나 상품을 이용할 수 있는 혜택입니다.

이러한 복지 혜택은 직원의 만족도를 높이고, 개인적인 여가 활동을 지원하기 위한 목적을 가지고 있습니다.✅
[26/30] Q: 타다 ‘프로덕트 디자이너’ 채용에서 직무 인터뷰 다음 … 타다의 '프로덕트 디자이너' 채용에서 컬쳐핏 인터뷰에는 함께 일하게 될 가능성이 높은 유관 부서의 동료와 HR팀이 참여합니다. 이 인터뷰의 주된 목적은 지원자의 가치관과 협업 시너지에 대한 이해를 검증하는 것입니다. 즉, 지원자가 타다의 조직 문화와 잘 맞는지, 그리고 팀 내에서 효과적으로 협업할 수 있는지를 평가하는 것이 핵심입니다. 이러한 과정은 지원자가 회사의 비전과 목표에 부합하는지를 확인하는 데 중요한 역할을 합니다.✅
[27/30] Q: 페이타랩 ‘패스오더 프론트엔드 개발자’ 개발환경에서 빌… 페이타랩 ‘패스오더 프론트엔드 개발자’의 개발환경에서 사용되는 빌드·컨테이너 도구 두 가지는 **Webpack**과 **Docker**이며, 패키지 매니저 한 가지는 **Npm**입니다.✅
[28/30] Q: 강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너… 강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너로 성장할 수 있는 이유로 제시된 두 가지 근거는 다음과 같습니다:

1. **다양한 국가의 사용자 대상 서비스 개발**: 강남언니는 일본, 태국 등 다양한 국가의 사용자를 대상으로 서비스를 만들고 있으며, 이를 통해 각 나라의 문화적 맥락을 이해하고 그에 맞는 제품을 디자인할 수 있는 기회를 제공합니다.

2. **데이터와 리서치를 기반으로 한 글로벌 제품 개발**: 강남언니는 데이터와 리서치를 기반으로 글로벌 제품을 만들고자 하는 프로덕트 디자이너를 기다리고 있으며, 이러한 접근은 디자이너가 글로벌 시장에서 경쟁력을 갖추고 성장할 수 있는 기반이 됩니다.

이 두 가지 요소는 강남언니에서의 경험이 글로벌 디자인 역량을 키우는 데 중요한 역할을 한다는 것을 보여줍니다.✅
[29/30] Q: 씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’… 씨제이올리브영의 'UI/UX 디자이너(신사업 프로덕트)' 자격 요건에서 '정량적·정성적 데이터 기반 개선 경험'은 필수 Experience 범주에 속합니다. 이 포지션의 최소 경력은 4년 이상의 UI/UX 디자인 또는 프로덕트 디자인 경험이 요구됩니다.✅
[30/30] Q: 미리디 ‘미리캔버스 프론트엔드팀’이 Turborepo를… Turborepo를 CICD 환경에서 활용함으로써 모듈 배포 효율화는 여러 가지 긍정적인 영향을 미칩니다. 첫째, Turborepo는 모노레포 환경을 지원하여 여러 패키지를 하나의 저장소에서 관리할 수 있게 해줍니다. 이를 통해 코드의 일관성을 유지하고, 의존성 관리가 용이해집니다.

둘째, Turborepo는 빌드 속도를 최적화하는 기능을 제공하여, 변경된 모듈만을 선택적으로 빌드할 수 있습니다. 이로 인해 전체 애플리케이션을 다시 빌드할 필요가 없어지며, 개발자들은 더 빠르게 피드백을 받을 수 있습니다.

셋째, 효율적인 모듈 배포는 CI/CD 파이프라인에서의 자동화와 통합이 용이해지므로, 배포 과정에서의 오류를 줄이고, 안정성을 높입니다. 이는 결과적으로 개발 및 배포 속도를 극대화하여, 빠르게 변화하는 서비스 환경에 적응할 수 있는 능력을 강화합니다.

마지막으로, 이러한 효율화는 팀의 생산성을 높이고, 개발자들이 더 많은 시간을 새로운 기능 개발이나 버그 수정에 집중할 수 있도록 도와줍니다. 따라서 Turborepo의 도입은 미리캔버스 프론트엔드팀의 전반적인 개발 및 배포 프로세스를 개선하는 데 중요한 역할을 합니다.✅
[LangSmith] 'rag_qac_dataset_Retriever_3' 업로드 완료! (총 30개)

# LangSmith 데이터셋에서 가져오기 이름만 바꾸면 됨

In [36]:
# 1. LangSmith 클라이언트 준비
from langsmith import Client
import pandas as pd  # 표로 보고 싶다면

client = Client()

# 2. 데이터셋 객체 찾기  ───────────────────────────────
DATASET_NAME = "rag_qac_dataset_simple_chunk_Retriever_1"  # ↔︎ 실제 이름
ds = next(ds for ds in client.list_datasets() if ds.name == DATASET_NAME)

# 3. 예제(샘플) 목록 가져오기
examples = client.list_examples(dataset_id=ds.id)

# 4. 원하는 컬럼만 추려서 확인
records = []
for ex in examples:
    q = ex.inputs.get("question", "")
    a = ex.outputs.get("answer", "")
    ctx = ex.outputs.get("context", "")  # 또는 ex.outputs["context"]
    records.append({"question": q, "context": ctx, "answer": a})

# 5-a. 터미널에서 빠르게 보기
for r in records[:3]:
    print("Q:", r["question"])
    print("A:", r["answer"][:80], "…")
    print("CTX:", r["context"][:80], "…")
    print("-" * 40)

# 5-b. 판다스 데이터프레임으로
df = pd.DataFrame(records)
df

Q: 미리디 ‘미리캔버스 프론트엔드팀’이 Turborepo를 CICD 환경에서 활용함으로써 모듈 배포 효율화가 개발 및 배포 속도에 주는 영향은 무엇이라고 설명하는가?
A: 미리디의 미리캔버스 프론트엔드팀이 Turborepo를 CICD 환경에서 활용함으로써 모듈 배포 효율화를 이루는 것은 여러 가지 긍정적인 영향을  …
CTX: 게시글 ID: 282656
제목: 미리캔버스 프론트엔드 개발자
포지션 상세 설명: 미리캔버스 프론트엔드팀이 해결하려는 문제 빠르게 성장하는 서비 …
----------------------------------------
Q: 씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’ 자격 요건에서 ‘정량적·정성적 데이터 기반 개선 경험’은 어느 범주에 속하며, 필수 Experience 최소 경력은 몇 년인가?
A: 씨제이올리브영의 ‘UI/UX 디자이너(신사업 프로덕트)’ 자격 요건에서 ‘정량적·정성적 데이터 기반 개선 경험’은 필수 Experience 범주 …
CTX: 자격 요건: ['712년 이내 Front Application 개발 경력', ' javascripttypescript 중에 숙련된 개발 경험 보 …
----------------------------------------
Q: 강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너로 성장할 수 있는 이유로 제시된 두 가지 근거는 무엇인가?
A: 강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너로 성장할 수 있는 이유로 제시된 두 가지 근거는 다음과 같습니다:

1. **다양한 국가 …
CTX: 수 있어요 리서치나 실험을 직접 설계하여 고객이 원하는 것을 발견하고, 가설을 검증하는 솔루션에 집중해 고객과 가장 가까운 곳에서 디자이너로서  …
----------------------------------------

,question,context,answer
0,미리디 ‘미리캔버스 프론트엔드팀’이 Turborepo를 CICD 환경에서 활용함으로...,게시글 ID: 282656\n제목: 미리캔버스 프론트엔드 개발자\n포지션 상세 설명...,미리디의 미리캔버스 프론트엔드팀이 Turborepo를 CICD 환경에서 활용함으로써...
1,씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’ 자격 요건에서 ‘정량적·정성...,"자격 요건: ['712년 이내 Front Application 개발 경력', ' j...",씨제이올리브영의 ‘UI/UX 디자이너(신사업 프로덕트)’ 자격 요건에서 ‘정량적·정...
2,강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너로 성장할 수 있는 이유로 제...,"수 있어요 리서치나 실험을 직접 설계하여 고객이 원하는 것을 발견하고, 가설을 검증...",강남언니 ‘프로덕트 디자이너 주니어’가 글로벌 디자이너로 성장할 수 있는 이유로 제...
3,페이타랩 ‘패스오더 프론트엔드 개발자’ 개발환경에서 빌드·컨테이너 도구 두 가지와 ...,회사명: 페이타랩패스오더\n근무지: 서울\n지역: 강남구\n직군: 개발\n직무: [...,페이타랩 ‘패스오더 프론트엔드 개발자’의 개발환경에서 사용되는 빌드 도구는 **We...
4,타다 ‘프로덕트 디자이너’ 채용에서 직무 인터뷰 다음 단계인 컬쳐핏 인터뷰에는 어떤...,"복지: ['# 몰입을 위한 모든 것을 지원하는 타다 BOOST PACK ', '',...",타다의 '프로덕트 디자이너' 채용에서 컬쳐핏 인터뷰에는 주로 두 그룹의 참여자가 포...
5,여기어때 ‘Product Owner 파트너서비스’ 복지에서 연간 100만 포인트와 ...,"우대 사항: ['국내외 주요 이커머스 서비스의 백오피스셀러오피스 경험이 있는 분',...",여기어때컴퍼니의 'Product Owner 파트너서비스' 직무에서 제공되는 연간 1...
6,미리디 ‘미리캔버스 프론트엔드팀’이 Micro Frontends 아키텍처 구현에 활...,게시글 ID: 282656\n제목: 미리캔버스 프론트엔드 개발자\n포지션 상세 설명...,미리디의 미리캔버스 프론트엔드팀이 Micro Frontends 아키텍처 구현에 활용...
7,토스페이먼츠 Frontend Developer 포지션에서 ‘결제 위젯’과 ‘대시보드...,"주요 업무: ['지금까진 이런 일을 했어요', '누구나 쉽게 원하는 결제 경험을 만...",토스페이먼츠의 Frontend Developer 포지션에서 '결제 위젯'과 '대시보...
8,111퍼센트 ‘웹 프론트 개발자’ 공고에 따르면 사옥은 2025년 8월경 어디로 확...,채용절차: ['서류전형 과제전형필요시 1차 인터뷰직무 2차 인터뷰컬처핏 처우...,"111퍼센트의 '웹 프론트 개발자' 공고에 따르면, 사옥은 2025년 8월경 성수동..."
9,컬리 ‘프로모션 기획 마케터’가 월 단위 주요 프로모션 테마를 기획할 때 포함하는 ...,게시글 ID: 283170\n제목: 프로모션 기획 마케터\n포지션 상세 설명: 컬리...,컬리의 '프로모션 기획 마케터'가 월 단위 주요 프로모션 테마를 기획할 때 포함해야...
10,미리디 복지 정책 중 ‘유연근무제도’가 허용하는 시차 출근 가능 시간 범위는?,"복지: ['미리디는 복지를 통해 나눔의 경영을 실현하고 있습니다', '', '자율과...",미리디의 유연근무제도에서는 시차 출퇴근이 오전 8시부터 11시까지 가능하다고 합니다...
11,씨제이올리브영 ‘커머스디자이너’ 우대 사항에서 ‘디자인 시스템 또는 UI 가이드 제...,게시글 ID: 286101\n제목: 커머스디자이너\n포지션 상세 설명: All Li...,씨제이올리브영의 '커머스디자이너' 포지션에서 요구하는 '디자인 시스템 또는 UI 가...
12,강남언니 ‘프로덕트 디자이너 주니어’가 데이터 기반 의사결정을 위해 활용할 수 있는...,"주요 업무: ['고객을 이해하기 위한 인터뷰, UT 등의 정성정량 UX 리서치 진행...",강남언니의 '프로덕트 디자이너 주니어'가 데이터 기반 의사결정을 위해 활용할 수 있...
13,페이타랩 ‘패스오더’ 프로덕트팀이 지양한다고 밝힌 업무 프로세스는 어떤 특성을 띠는가?,"회사명: 페이타랩패스오더\n\n주요 업무: ['페이타랩 프로덕트팀', '', '프로...",페이타랩 '패스오더' 프로덕트팀이 지양하는 업무 프로세스는 불필요하고 복잡한 특성을...
14,타다 ‘프로덕트 디자이너’의 문제 해결 프로세스에서 첫 번째로 설정·발굴해야 하는 ...,게시글 ID: 282809\n제목: 프로덕트 디자이너PD\n포지션 상세 설명: 모든...,타다의 프로덕트 디자이너가 문제 해결 프로세스에서 첫 번째로 설정하고 발굴해야 하는...
15,여기어때 ‘Product Owner 파트너서비스’ 포지션에서 파트너 행동 데이터를 ...,게시글 ID: 286509\n제목: Product Owner 파트너서비스\n포지션 ...,여기어때 ‘Product Owner 파트너서비스’ 포지션에서 파트너 행동 데이터를 ...
16,미리디 ‘미리캔버스 프론트엔드팀’이 글로벌 성능 최적화를 위해 도입한 렌더링 기법은...,포지션 상세 설명: 회사 소개전 세계로 확장 중인 디자인 올인원 플랫폼 미리디는 모...,미리디의 미리캔버스 프론트엔드팀이 글로벌 성능 최적화를 위해 도입한 렌더링 기법은 ...
17,토스페이먼츠 Frontend Developer 포지션에서 챕터가 주기적으로 진행하는...,게시글 ID: 279483\n제목: Frontend Developer\n포지션 상세...,토스페이먼츠의 Frontend Developer 포지션에서 챕터가 주기적으로 진행하...
18,111퍼센트 ‘웹 프론트 개발자’ 우대 사항으로 언급된 세 가지 경험 유형은 무엇인가?,"우대 사항: ['이런 분이면 더 좋아요 ', '\u3000', ' 반응형 디자인, ...",111퍼센트의 '웹 프론트 개발자' 포지션에서 우대 사항으로 언급된 세 가지 경험 ...
19,컬리 ‘프로모션 기획 마케터’는 성과 분석 시 어떤 두 가지 핵심 지표를 관리하도록...,게시글 ID: 285974\n제목: 컬리 커머스 영업기획 담당자\n포지션 상세 설명...,컬리 ‘프로모션 기획 마케터’의 성과 분석 시 관리해야 할 두 가지 핵심 지표는 R...
20,씨제이올리브영 ‘UI/UX 디자이너(신사업 프로덕트)’ 포지션의 주요 디자인 툴 두...,게시글 ID: 278301\n제목: UIUX 디자이너신사업 프로덕트\n포지션 상세 ...,씨제이올리브영의 'UI/UX 디자이너(신사업 프로덕트)' 포지션에서 요구되는 주요 ...
21,강남언니 ‘프로덕트 디자이너 주니어’ 포지션의 기본 출근 기준 시간은 오전 몇 시인가?,있는 기획력을 갖추신 분 성실함과 책임감이 강한 분 디자인에 대한 융통성이 있는 ...,강남언니의 '프로덕트 디자이너 주니어' 포지션의 기본 출근 기준 시간은 오전 9시 ...
22,페이타랩 ‘패스오더 프론트엔드 개발자’가 주로 사용하는 두 가지 기본 프로그래밍 언어는?,회사명: 페이타랩패스오더\n근무지: 서울\n지역: 강남구\n직군: 개발\n직무: [...,페이타랩의 '패스오더 프론트엔드 개발자'가 주로 사용하는 두 가지 기본 프로그래밍 ...
23,타다 ‘프로덕트 디자이너’ 서류 제출 예시에서 ‘김타다이력서’와 짝을 이루는 포트폴...,"자격 요건: ['최소 3년 이상의 프로덕트 디자이너 경력이 있는 분', ' 심미적이...",타다 ‘프로덕트 디자이너’ 서류 제출 시 포트폴리오 파일명은 '김타다포트폴리오'와 ...
24,여기어때 ‘Product Owner 파트너서비스’ 포지션에서 월요일 공식 출근 시간...,게시글 ID: 286509\n제목: Product Owner 파트너서비스\n포지션 ...,여기어때 ‘Product Owner 파트너서비스’ 포지션에서 월요일 공식 출근 시간...
25,미리디 ‘미리캔버스 프론트엔드팀’이 모노레포 구현을 위해 도입한 도구는?,게시글 ID: 282656\n제목: 미리캔버스 프론트엔드 개발자\n포지션 상세 설명...,"미리디의 미리캔버스 프론트엔드팀이 모노레포 구현을 위해 도입한 도구는 ""Turbor..."
26,토스페이먼츠 ‘Frontend Developer’ 포지션이 사용하는 상태 관리 라이...,"우대 사항: ['이런 경험이 있다면 이력서에 꼭 작성해 주세요', 'TypeScri...",토스페이먼츠의 'Frontend Developer' 포지션에서 사용하는 상태 관리 ...
27,111퍼센트 ‘웹 프론트 개발자’ 포지션에서 주 사용 프레임워크는?,게시글 ID: 283738\n제목: 웹 프론트 개발자\n포지션 상세 설명: 111퍼...,111퍼센트의 '웹 프론트 개발자' 포지션에서 주 사용 프레임워크는 React입니다...
28,씨제이올리브영 ‘커머스디자이너’ 포지션 지원 시 필수로 제출해야 하는 것은?,게시글 ID: 286101\n제목: 커머스디자이너\n포지션 상세 설명: All Li...,씨제이올리브영의 '커머스디자이너' 포지션에 지원할 때 필수로 제출해야 하는 것은 포...
29,컬리 ‘프로모션 기획 마케터’ 포지션의 최소 필요 경력(년)은?,"특징: ['의료비지원', '휴가비', '유급휴가', '커피스낵바', '1,00110...","컬리의 '프로모션 기획 마케터' 포지션에 대한 정보는 제공되지 않았습니다. 그러나,..."

# LLM 평가기

In [50]:
import pandas as pd
import json
import time
import re
from typing import Dict, List, Optional
import google.generativeai as genai
import openai
from langsmith import Client


class RAGEvaluator:
    def __init__(self, llm_provider: str = "gemini", api_key: str = None):
        """
        RAG 평가기 초기화

        Args:
            llm_provider: "gemini" 또는 "perplexity"
            api_key: API 키
        """
        self.llm_provider = llm_provider.lower()

        if self.llm_provider == "gemini":
            genai.configure(api_key=api_key)
            self.model = genai.GenerativeModel('gemini-2.0-flash')
        elif self.llm_provider == "perplexity":
            self.client = openai.OpenAI(
                api_key=api_key,
                base_url="https://api.perplexity.ai"
            )
        else:
            raise ValueError("llm_provider는 'gemini' 또는 'perplexity'여야 합니다.")

    def create_evaluation_prompt(self, question: str, context: str, answer: str, metric_type: str) -> str:
        """평가 메트릭별 프롬프트 생성 (개선된 버전)"""

        base_instruction = f"""
다음 RAG 시스템의 성능을 평가해주세요.

**질문 (Question):**
{question}

**검색된 맥락 (Context):**
{context}

**생성된 답변 (Answer):**
{answer}

---
"""

        if metric_type == "faithfulness":
            specific_instruction = """
**평가 기준: 신뢰성 (Faithfulness)**
생성된 답변이 검색된 맥락 데이터에 얼마나 사실적으로 부합하는지 평가하세요.
- 10점: 답변의 모든 내용이 맥락에서 직접 뒷받침됨
- 8-9점: 답변의 대부분이 맥락에 부합하며, 약간의 추론이 있음
- 6-7점: 답변의 일부가 맥락에 부합하지만 일부 내용이 불분명
- 4-5점: 답변의 일부만 맥락에 부합하며 상당한 추측이 포함됨
- 2-3점: 답변이 맥락과 크게 다르거나 모순됨
- 0-1점: 답변이 맥락과 전혀 부합하지 않음
"""

        elif metric_type == "answer_relevance":
            specific_instruction = """
**평가 기준: 답변 관련성 (Answer Relevance)**
생성된 답변이 질문과 얼마나 관련성이 있고 적절한지 평가하세요.
- 10점: 질문에 완벽하게 답변하며 정확하고 완전함
- 8-9점: 질문에 잘 답변하지만 약간의 부족한 부분이 있음
- 6-7점: 질문에 부분적으로 답변하지만 핵심을 놓침
- 4-5점: 질문과 관련은 있지만 부적절하거나 불완전함
- 2-3점: 질문과 약간 관련이 있지만 대부분 부적절함
- 0-1점: 질문과 전혀 관련이 없음
"""

        elif metric_type == "context_relevance":
            specific_instruction = """
**평가 기준: 맥락 관련성 (Context Relevance)**
검색된 맥락 데이터가 질문과 얼마나 관련이 있고 유용한지 평가하세요.
- 10점: 맥락이 질문에 완벽하게 관련되고 답변에 필요한 모든 정보 포함
- 8-9점: 맥락이 질문에 매우 관련되며 대부분의 필요한 정보 포함
- 6-7점: 맥락이 질문에 관련되지만 일부 정보가 부족하거나 불필요함
- 4-5점: 맥락이 질문에 부분적으로만 관련됨
- 2-3점: 맥락이 질문과 약간만 관련됨
- 0-1점: 맥락이 질문과 전혀 관련이 없음
"""

        # 더 명확한 출력 형식 지시
        output_format = """
**중요: 다음 형식으로 정확히 응답하세요**

반드시 아래 JSON 형식으로만 응답하고, 다른 텍스트는 포함하지 마세요:

{"score": [0부터 10까지의 숫자], "reasoning": "평가 근거"}

예시:
{"score": 7, "reasoning": "답변이 대부분 정확하지만 일부 세부사항이 부족함"}
"""

        return base_instruction + specific_instruction + output_format

    def get_llm_response(self, prompt: str) -> str:
        """LLM에서 응답 받기"""
        try:
            if self.llm_provider == "gemini":
                response = self.model.generate_content(prompt)
                return response.text

            elif self.llm_provider == "perplexity":
                response = self.client.chat.completions.create(
                    model="llama-3.1-sonar-large-128k-online",  # 또는 다른 모델
                    messages=[
                        {"role": "system",
                         "content": "당신은 RAG 시스템 평가 전문가입니다. 정확하고 객관적인 평가를 수행하세요. 반드시 JSON 형식으로만 응답하세요."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.1
                )
                return response.choices[0].message.content

        except Exception as e:
            print(f"LLM 응답 오류: {e}")
            return None

    def parse_llm_response(self, response: str) -> Dict:
        """LLM 응답에서 점수와 근거 추출 (가장 견고한 버전)"""

        def clean_response(text: str) -> str:
            """응답 텍스트 정리"""
            text = text.strip()

            # Markdown 코드 블록 제거
            if text.startswith('```json'):
                text = text[7:]
            elif text.startswith('```'):
                text = text[3:]

            if text.endswith('```'):
                text = text[:-3]

            return text.strip()

        def extract_json_objects(text: str) -> List[str]:
            """텍스트에서 모든 JSON 객체 추출"""
            json_objects = []
            brace_count = 0
            start_pos = -1

            for i, char in enumerate(text):
                if char == '{':
                    if brace_count == 0:
                        start_pos = i
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
                    if brace_count == 0 and start_pos != -1:
                        json_objects.append(text[start_pos:i + 1])
                        start_pos = -1

            return json_objects

        def try_parse_json(json_str: str) -> Optional[Dict]:
            """JSON 파싱 시도"""
            try:
                return json.loads(json_str)
            except:
                return None

        try:
            # 1. 응답 정리
            clean_text = clean_response(response)

            # 2. JSON 객체들 추출
            json_candidates = extract_json_objects(clean_text)

            # 3. 각 JSON 객체 파싱 시도
            for json_str in json_candidates:
                result = try_parse_json(json_str)
                if result and 'score' in result:
                    # 점수 유효성 검사
                    score = result.get('score', 0)
                    if isinstance(score, (int, float)) and 0 <= score <= 10:
                        return {
                            'score': float(score),
                            'reasoning': result.get('reasoning', 'No reasoning provided')
                        }

            # 4. 정규표현식으로 점수와 이유 추출 (백업 방법)
            score_match = re.search(r'"score"\s*:\s*(\d+(?:\.\d+)?)', clean_text)
            reasoning_match = re.search(r'"reasoning"\s*:\s*"([^"]*)"', clean_text)

            if score_match:
                score = float(score_match.group(1))
                reasoning = reasoning_match.group(1) if reasoning_match else "추출된 점수"

                if 0 <= score <= 10:
                    return {
                        'score': score,
                        'reasoning': reasoning
                    }

            # 5. 모든 시도 실패
            raise ValueError("유효한 점수를 찾을 수 없습니다.")

        except Exception as e:
            print(f"파싱 오류: {e}")
            print(f"원본 응답: {response[:500]}...")  # 처음 500자만 출력
            return {'score': 0.0, 'reasoning': 'Parsing failed'}

    def evaluate_single_example(self, question: str, context: str, answer: str) -> Dict:
        """단일 예제에 대한 전체 평가"""
        metrics = ['faithfulness', 'answer_relevance', 'context_relevance']
        results = {}

        for metric in metrics:
            print(f"  평가 중: {metric}")

            prompt = self.create_evaluation_prompt(question, context, answer, metric)
            response = self.get_llm_response(prompt)

            if response:
                parsed = self.parse_llm_response(response)
                results[metric] = parsed
            else:
                results[metric] = {'score': 0.0, 'reasoning': 'LLM response failed'}

            # API 호출 간격 (rate limiting 방지)
            time.sleep(1)

        return results

    def evaluate_dataset(self, records: List[Dict]) -> pd.DataFrame:
        """전체 데이터셋 평가"""
        all_results = []

        for i, record in enumerate(records):
            print(f"\n평가 진행 중... ({i + 1}/{len(records)})")

            question = record['question']
            context = record['context']
            answer = record['answer']

            # 각 메트릭별 평가
            evaluation_results = self.evaluate_single_example(question, context, answer)

            # 결과 저장
            result_row = {
                'question': question,
                'context': context,
                'answer': answer,
                'faithfulness_score': evaluation_results['faithfulness']['score'],
                'faithfulness_reasoning': evaluation_results['faithfulness']['reasoning'],
                'answer_relevance_score': evaluation_results['answer_relevance']['score'],
                'answer_relevance_reasoning': evaluation_results['answer_relevance']['reasoning'],
                'context_relevance_score': evaluation_results['context_relevance']['score'],
                'context_relevance_reasoning': evaluation_results['context_relevance']['reasoning'],
                'average_score': (
                                         evaluation_results['faithfulness']['score'] +
                                         evaluation_results['answer_relevance']['score'] +
                                         evaluation_results['context_relevance']['score']
                                 ) / 3
            }

            all_results.append(result_row)

        return pd.DataFrame(all_results)

    def get_summary_statistics(self, df: pd.DataFrame) -> Dict:
        """평가 결과 요약 통계"""
        return {
            'faithfulness': {
                'mean': df['faithfulness_score'].mean(),
                'std': df['faithfulness_score'].std(),
                'min': df['faithfulness_score'].min(),
                'max': df['faithfulness_score'].max()
            },
            'answer_relevance': {
                'mean': df['answer_relevance_score'].mean(),
                'std': df['answer_relevance_score'].std(),
                'min': df['answer_relevance_score'].min(),
                'max': df['answer_relevance_score'].max()
            },
            'context_relevance': {
                'mean': df['context_relevance_score'].mean(),
                'std': df['context_relevance_score'].std(),
                'min': df['context_relevance_score'].min(),
                'max': df['context_relevance_score'].max()
            },
            'overall': {
                'mean': df['average_score'].mean(),
                'std': df['average_score'].std(),
                'min': df['average_score'].min(),
                'max': df['average_score'].max()
            }
        }

In [51]:
from Run_Pipeline.Env_Loader import EnvLoader

EnvLoader.load_local(dotenv_path="../.env")

In [53]:
import os


def main():
    # 1. LangSmith에서 데이터셋 가져오기 (기존 코드)
    client = Client()
    DATASET_NAME = "rag_qac_dataset_Retriever_4"  # 실제 데이터셋 이름으로 교체
    ds = next(ds for ds in client.list_datasets() if ds.name == DATASET_NAME)
    examples = client.list_examples(dataset_id=ds.id)

    records = []
    for ex in examples:
        q = ex.inputs.get("question", "")
        a = ex.outputs.get("answer", "")
        ctx = ex.outputs.get("context", "")
        records.append({"question": q, "context": ctx, "answer": a})

    # 2. 평가기 초기화
    API_KEY = os.getenv("PPLX_API_KEY")  # 실제 API 키로 교체

    # Gemini 사용하는 경우
    #evaluator = RAGEvaluator(llm_provider="gemini", api_key=API_KEY)

    # Perplexity 사용하는 경우
    evaluator = RAGEvaluator(llm_provider="perplexity", api_key=API_KEY)

    # 3. 평가 실행 (전체 데이터셋 또는 샘플)
    #sample_records = records[:5]  # 테스트용으로 5개만
    sample_records = records  # 전체 데이터셋 평가

    print("RAG 시스템 평가를 시작합니다...")
    results_df = evaluator.evaluate_dataset(sample_records)

    # 4. 결과 저장 및 요약

    # 요약 통계
    print("\n=== 평가 결과 요약 ===")
    print(f"총 평가 항목 수: {len(results_df)}")
    print(f"신뢰성 평균 점수: {results_df['faithfulness_score'].mean():.2f}")
    print(f"답변 관련성 평균 점수: {results_df['answer_relevance_score'].mean():.2f}")
    print(f"맥락 관련성 평균 점수: {results_df['context_relevance_score'].mean():.2f}")
    print(f"전체 평균 점수: {results_df['average_score'].mean():.2f}")

    # 상세 결과 출력
    print("\n=== 상세 결과 ===")
    print(
        results_df[['faithfulness_score', 'answer_relevance_score', 'context_relevance_score', 'average_score']].head())

    return results_df


if __name__ == "__main__":
    results = main()

RAG 시스템 평가를 시작합니다...

평가 진행 중... (1/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (2/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (3/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (4/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (5/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (6/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (7/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (8/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (9/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (10/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (11/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (12/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (13/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (14/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (15/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (16/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (17/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (18/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (19/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (20/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (21/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (22/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (23/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (24/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (25/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (26/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (27/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (28/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (29/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

평가 진행 중... (30/30)
  평가 중: faithfulness
  평가 중: answer_relevance
  평가 중: context_relevance

=== 평가 결과 요약 ===
총 평가 항목 수: 30
신뢰성 평균 점수: 8.70
답변 관련성 평균 점수: 9.20
맥락 관련성 평균 점수: 9.03
전체 평균 점수: 8.98

=== 상세 결과 ===
   faithfulness_score  answer_relevance_score  context_relevance_score  \
0                 9.0                    10.0                      9.0
1                 9.0                     9.0                      8.0
2                 9.0                    10.0                      9.0
3                10.0                    10.0                     10.0
4                 9.0                    10.0                      9.0

   average_score
0       9.333333
1       8.666667
2       9.333333
3      10.000000
4       9.333333

In [28]:
results.head(32)

,question,context,answer,faithfulness_score,faithfulness_reasoning,answer_relevance_score,answer_relevance_reasoning,context_relevance_score,context_relevance_reasoning,average_score
0,영상화/멀티미디어 제작사 관련 공고 보여줘,게시글 ID: 268045\n제목: 제작 PD 광고 및 홍보 영상 콘텐츠 제작\n...,현재 영상화 및 멀티미디어 제작사와 관련된 공고는 다음과 같습니다:\n\n1. **...,9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 회사명, 근무지, 직...",9.0,"생성된 답변은 질문에 완벽하게対応하며, 필요한 정보를 정확하고 완전하게 제공합니다....",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 모든 정보를 포함하고 있습니다....",9.000000
1,서울에 있는 GMO/식품/바이오 관련 회사 공고 정리해줘,회사명: 강남엄마\n\n회사명: 이스턴생명과학\n회사 소개: IT 업체\n업종(산업...,서울에 있는 GMO/식품/바이오 관련 회사의 공고를 정리하기 위해서는 해당 산업에 ...,8.0,"답변이 대부분 검색된 맥락에 부합하며, 지놈오피니언에 대한 상세한 정보를 제공함. ...",8.0,"답변이 질문과 관련되어 있으며, 지놈오피니언과 같은 바이오 관련 회사에 대한 상세한...",6.0,"답변이 질문에 관련되지만, 제공된 맥락 데이터에서 서울에 있는 GMO/식품/바이오 ...",7.333333
2,UX디자이너 채용 공고 좀 보여줘,"근무지: 서울\n지역: 강남구\n직군: 디자인\n직무: ['웹 디자이너', 'UX ...",현재 강남구에서 UX 디자이너 채용 공고는 다음과 같습니다:\n\n1. **게시글 ...,6.0,"답변이 일부 세부사항에서 맥락과 부합하지 않음. 예를 들어, 특정 회사나 상세한 채...",9.0,"생성된 답변은 질문에 완벽하게対応하며, 필요한 정보를 정확하고 완전하게 제공합니다....",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 모든 정보를 포함하고 있습니다....",8.000000
3,디지털 마케팅 인턴 공고를 보여줘,게시글 ID: 268926\n제목: 인턴 한국 마케팅\n\n게시글 ID: 28944...,"현재 디지털 마케팅 인턴 공고를 직접 보여드릴 수는 없지만, 일반적으로 디지털 마케...",2.0,"답변이 맥락과 크게 다르며, 제공된 검색 결과와 직접적인 연결이 없음. 검색 결과에...",4.0,답변이 질문과 관련은 있지만 부적절하거나 불완전함. 실제 디지털 마케팅 인턴 공고의...,4.0,검색된 맥락 데이터가 디지털 마케팅 인턴 공고의具体적인 내용이나 자격 요건을 제공하...,3.333333
4,서울 금천구에 있는 PR회사 공고를 보여줘,회사명: 마인드리퍼블릭 existing\n회사 소개: 이커머스 PR 에이전시 리...,서울 금천구에 있는 PR 회사의 공고는 위더스애드에서 확인할 수 있습니다. 아래는 ...,9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 약간의 추론이 포함됨...",10.0,생성된 답변이 질문에 완벽하게 답변하며 정확하고 완전함. 질문에서 요청한 서울 금천...,9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 정보 대부분을 포함하고 있습니다...",9.333333
5,재택 근무를 할 수 있는 회사 공고 알려줘,"복지: ['재택근무제주1일 출근, 6개월 이상 재직자 대상', ' 시간연차 사용 지...",재택 근무를 지원하는 회사로는 다음과 같은 두 곳이 있습니다:\n\n1. **앨리슨...,9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 회사명, 근무지, 직...",9.0,"생성된 답변이 질문에 완벽하게対応하며, 재택 근무를 지원하는 회사들의 주요 정보를 ...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 재택 근무를 지원하는 회사들의 상세 정...",9.000000
6,고졸로 지원할 수 있는 대기업 공고를 알려줘,"특징: ['유급휴가', '커피스낵바', '식대지원', '설립10년이상', '연봉 업...","현재 제공된 정보에 따르면, 고졸로 지원할 수 있는 대기업 공고는 없습니다. 대부분...",2.0,"답변이 제공된 맥락과 크게 다르며, 모순된 내용이 포함됨. 제공된 데이터에는 고졸로...",4.0,"생성된 답변은 질문에 직접적으로 응답하지 못하고, 제공된 컨텍스트와 무관한 일반적인...",0.0,제공된 맥락 데이터가 질문과 전혀 관련이 없음. 질문은 고졸로 지원할 수 있는 대기...,2.000000
7,Growth Marketer직무 관련 공고 보여줘,게시글 ID: 285592\n제목: B2B SaaS Growth Marketing ...,현재 서울 성동구에서의 Growth Marketer 직무 관련 공고는 다음과 같습니...,9.0,"답변이 검색된 맥락 데이터에 대부분 사실적으로 부합하며, 약간의 추론이 포함됨. 게...",4.0,"생성된 답변은 실제로 검색된 자료와 일치하지 않으며, 제공된.context와도 맞지...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 대부분의 정보를 포함하고 있습니...",7.333333
8,프레인글로벌에 입사하고 싶은데 다른 나라에도 지사가 있는지 알고 싶어,회사명: 프레인글로벌\n근무지: 서울\n지역: 중구\n직군: 마케팅광고\n직무: [...,"프레인글로벌은 국내 1위 PR 기업으로, 해외 PR AWARDS에서 대상을 수상한 ...",6.0,"답변이 일부 맥락에 부합하지만, 프레인글로벌의海外 지사에 대한 정보가 명확히 제공되...",7.0,답변이 대부분 정확하지만 프레인글로벌의 해외 지사 여부에 대한 명확한 정보가 부족함...,4.0,검색된 맥락 데이터에 프레인글로벌의 해외 지사 또는 글로벌 사업에 대한 정보가 포함...,5.666667
9,KB국민은행에 어떤 직군이 있는지 알려줘,회사명: KB국민은행\n회사 소개: 금융을 통해 고객의 행복한 미래를 설계하고 보다...,"KB국민은행은 다양한 직군을 운영하고 있으며, 주요 직군은 다음과 같습니다:\n\n...",8.0,"답변이 대부분 검색된 맥락에 부합하지만, 일부 세부사항이 추가적으로 추론되거나 상세...",8.0,"답변이 대부분 정확하게 KB국민은행의 주요 직군을 설명했지만, 일부 세부적인 직무介...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되어 있으며, 대부분의 필요한 정보를 포함하고...",8.333333
10,넥슨의 복지 제도를 알려줘,"복지: ['1 지원금보험', '각종 경조사 지원, 업무활동비 지급, 문화생활비,',...","넥슨의 복지 제도는 직원들의 삶의 질을 높이고, 업무 효율성을 극대화하기 위해 다양...",8.0,"답변이 검색된 맥락 데이터의 대부분을 정확하게 반영하고 있으나, 일부 세부사항이 약...",9.0,"생성된 답변이 질문에 매우 잘対応하며, 넥슨의 복지 제도를 詳細하게 설명하고 있습니...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 답변에 필요한 대부분의 정보를 포함하고...",8.666667
11,부산에서 취업을 하려는데 정보처리기사 자격증을 가지고 있으면 우대해주는 회사가 있을까?,"우대 사항: ['개인정보보호 관련 자격증을 보유하신 분CPPG, ISMSP 심사원 ...",부산에서 정보처리기사 자격증을 보유한 지원자를 우대하는 회사는 여러 곳이 있을 수 ...,6.0,"답변이 일부 맥락에 부합하지만, 특정한 예시가 부족하고 추측이 포함됨. 예를 들어,...",8.0,"답변이 질문에 잘対応하고 있으며, 정보처리기사 자격증의 우대사항을 설명했습니다. 그...",6.0,검색된 맥락 데이터 중 일부는 정보처리기사 자격증의 일반적인 우대 사항과 관련이 있...,6.666667
12,SK 인포섹 회사에 대해서 알려줘,회사명: SK인포섹\n회사 소개: SK인포섹은 미래창조과학부 지정 정보보안전문업체로...,"SK인포섹은 2000년에 설립된 정보보안 전문 기업으로, 현재 26년의 업력을 가지...",9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 약간의 추론이 포함됨...",9.0,"생성된 답변은 질문에 완벽하게対応하며, SK인포섹의 회사 소개, 주요 서비스, 위치...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 대부분의 정보를 포함하고 있습니...",9.000000
13,식품안정성 평가 전문가 공고 보여줘,게시글 ID: 285429\n제목: 식품KFOOD 커머스 MD\n\n게시글 ID: ...,"현재 제가 가지고 있는 정보에는 ""식품안정성 평가 전문가""에 대한 구체적인 공고가 ...",2.0,"답변이 맥락과 크게 다르며, 검색된 맥락 데이터에 직접적으로 부합하지 않음. 제공된...",6.0,답변이 질문에 부분적으로 답변하지만 핵심인 '식품안정성 평가 전문가 공고'를 제공하...,2.0,"검색된 맥락 데이터가 질문에 거의 관련이 없으며, 제공된 맥락은 식품안정성 평가 전...",3.333333
14,IT 분야에서 일하면서 마케팅 관련 업무도 함께 할 수 있는 회사가 있을까?,회사명: 마케팅피플\n회사 소개: 최고의 종합 광고 전문대행사Marketing Se...,"네, IT 분야에서 일하면서 마케팅 관련 업무를 함께 할 수 있는 회사는 여러 곳이...",8.0,"답변이 검색된 맥락 데이터에 대부분 부합하며, 옥타코와 같은 회사에서 수행하는 마케...",8.0,"답변이 질문에 잘対応하며, IT 분야에서 마케팅 관련 업무를 할 수 있는 회사 예를...",8.0,"검색된 맥락 데이터는 질문에 매우 관련되며, 옥타코와 같은 회사에서 IT와 마케팅을...",8.000000
15,내가 지금 GTQ 자격증을 보유 중인데 지원할만한 IT 회사가 있을까?,"자격 요건: ['학력 학사 이상', ' 경력 IT 관련 기술영업 경력 3 년 이상'...",GTQ(Graphic Technology Qualification) 자격증은 주로 ...,8.0,"답변이 대부분 검색된 맥락에 부합하며, GTQ 자격증의 활용 가능성을 디자인과 관련...",8.0,"답변이 질문에 잘対応하며, GTQ 자격증이 IT 분야에서 어떻게 활용될 수 있는지에...",7.0,"답변이 GTQ 자격증의 활용 가능성을 설명하고, 관련된 IT 회사에서 어떻게 활용될...",7.666667
16,고객 경험 기획자 회사 중 가장 연매출이 높은 회사는 어디야?,회사명: 제일기획 exsting\n회사 소개: 제일기획은 클라이언트의 과제에 대한...,고객 경험 기획자와 관련된 회사 중에서 가장 높은 연매출을 기록한 회사는 제일기획입...,10.0,"답변이 검색된 맥락 데이터에 완전히 부합하며, 제일기획의 매출액이 다른 두 회사보다...",10.0,답변이 질문에 완벽하게 답변하며 정확하고 완전함. 제일기획의 매출액이 다른 회사들보...,9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 모든 정보를 포함하고 있습니다....",9.666667
17,세종에서 소프트웨어 엔지니어로 일할 수 있는 곳이 있어?,"근무지: 경기\n지역: 성남시\n직군: 개발\n직무: ['자바 개발자', '서버 개...",현재 세종에서 소프트웨어 엔지니어로 일할 수 있는 구체적인 채용 공고는 확인되지 않...,8.0,"답변이 검색된 맥락 데이터에 대부분 부합하며, 세종에서 직접적인 채용 기회는 없지만...",8.0,생성된 답변은 질문에 잘対応하여 세종에서 직접적인 소프트웨어 엔지니어 채용 기회는 ...,8.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 세종에서 소프트웨어 엔지니어로 일할 수...",8.000000
18,스포츠 마케팅 기업 공고 보여줘,게시글 ID: 262900\n제목: 마케팅 1팀헤어 케어 퍼포먼스 마케터\n\n회사...,현재 제가 가지고 있는 정보에는 스포츠 마케팅 관련 기업의 구체적인 공고가 포함되어...,2.0,"답변이 검색된 맥락과 크게 다르며, 제공된 데이터에서 직접적으로 뒷받침되는 내용이 ...",4.0,답변이 질문과 관련은 있지만 부적절하거나 불완전함. 제공된 정보는 구체적인 스포츠 ...,2.0,"검색된 맥락 데이터가 스포츠 마케팅 기업 공고와 전혀 관련이 없으며, 제공된 정보는...",2.666667
19,공공데이터 분석가 공고 좀 알려줘,"게시글 ID: 282256\n제목: 데이터 분석가그로스해커, 서울\n\n게시글 ID...",현재 제공된 정보에는 공공데이터 분석가에 대한 구체적인 채용 공고가 포함되어 있지 ...,6.0,"답변이 일부만 맥락에 부합하며, 공공데이터 분석가 채용 공고에 대한 구체적인 정보는...",6.0,"답변이 질문과 부분적으로 관련이 있지만,具体적인 공공데이터 분석가 채용 공고에 대한...",4.0,검색된 맥락 데이터가 제공된 질문에 직접적으로 관련된 정보를 포함하고 있지 않음. ...,5.333333
20,삼성 SDS 회사에 대한 정보 좀 알려줘,회사명: 삼성에스디에스\n회사 소개: 기술과 비즈니스를 융합하여 새로운 미래를 만드...,"삼성SDS는 1985년에 설립된 삼성의 ICT(정보통신기술) 전문 기업으로, 현재까...",9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 약간의 추론이 포함됨...",9.0,"생성된 답변은 질문에 매우 잘対応하며, 삼성 SDS의 회사 소개, 설립년도, 주요 ...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 삼성 SDS에 대한 필요한 모든 정보를...",9.000000
21,자동차 테스트 엔지니어 공고 좀 찾아줘,게시글 ID: 287956\n제목: 남양주 신입 Test Engineer\n포지션 ...,현재 확인할 수 있는 자동차 테스트 엔지니어 관련 공고는 다음과 같습니다:\n\n*...,10.0,"답변이 검색된 맥락 데이터에 완전히 부합하며, 모든 내용이 직접 뒷받침됨",8.0,답변이 질문에 잘対応하여 자동차 테스트 엔지니어 관련 공고의 주요 내용을 포함하고 ...,8.0,답변이 질문에 매우 관련되며 대부분의 필요한 정보를 포함하고 있습니다. 그러나 다른...,8.666667
22,내가 정보처리기사 자격증이랑 정보통신산업기사 자격증이 있는데 이 두 개의 자격증을...,"회사명: 한국정보통신자격협회\n회사 소개: PC정비사, 네트워크관리사 등 IT전문 ...","정보처리기사와 정보통신산업기사 자격증을 보유하고 계신다면, IT 및 정보통신 관련 ...",8.0,"답변이 대부분 검색된 맥락에 부합하며, 정보처리기사와 정보통신산업기사 자격증을 우대...",9.0,"답변이 질문에 완벽하게対応하며, 정보처리기사와 정보통신산업기사 자격증을 요구하는 회...",8.0,답변이 정보처리기사와 정보통신산업기사 자격증을 요구하는 회사에 regard하여 대부...,8.333333
23,스타트업 중에서 LLM 기반 개발자를 찾는 곳이 있어?,회사명: 알잘딱깔센 르지\n회사 소개: 스타트업으로 시니어 프로젝트를 같이할 Bac...,현재 제공된 정보에는 LLM(대형 언어 모델) 기반 개발자를 명시적으로 찾고 있는 ...,7.0,답변이 대부분 정확하지만 일부 세부사항이 부족함. 검색된 맥락에서 링크닷츠와 같은 ...,7.0,"답변이 질문과 관련은 있지만, LLM 기반 개발자를 명시적으로 찾고 있는 스타트업에...",6.0,검색된 맥락 데이터는 IT 및 콘텐츠 산업에 속하는 스타트업들에 대한 정보를 제공하...,6.666667
24,제조업 분야에서 AI 엔지니어를 채용하는 기업이 있을까요?,게시글 ID: 259098\n제목: AI Researcher Engineer 2년...,"네, 제조업 분야에서 AI 엔지니어를 채용하는 기업이 여러 곳 있습니다. 예를 들어...",9.0,"답변이 검색된 맥락 데이터에 대부분 부합하며, 나니아랩스와 럭스로보의 포지션 상세 ...",9.0,"답변이 질문에 완벽하게対応하며, 관련된 기업과 그들의 주요 업무 및 자격 요건을 정...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되어 있으며, 나니아랩스와 럭스로보 gibi ...",9.000000
25,경기도에서 프론트엔드 직무 채용 중인 회사가 있어?,회사명: 바이옴에이츠\n근무지: 경기\n지역: 과천시\n직군: 개발\n직무: ['프...,"네, 경기도에서 프론트엔드 직무 채용 중인 회사가 있습니다. 현재 다음 두 회사를 ...",9.0,"생성된 답변의 대부분이 검색된 맥락 데이터에 직접 뒷받침되며, 회사명, 근무지, 요...",9.0,"생성된 답변은 질문에 완벽하게対応하며, 필요한 정보를 정확하고 완전하게 제공합니다....",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 모든 정보를 포함하고 있습니다....",9.000000
26,울산에서 IT 컨설턴트 뽑는 채용 공고를 찾아줘,게시글 ID: 269484\n제목: 사업기획 컨설턴트\n\n게시글 ID: 28564...,"현재 울산에서 IT 컨설턴트 관련 채용 공고는 확인할 수 없습니다. 하지만, 울산 ...",2.0,"생성된 답변은 검색된 맥락 데이터와 크게 다르며, 모순됨. 검색된 맥락에는 울산과 ...",6.0,"답변이 질문과 부분적으로 관련이 있지만, 핵심적으로 울산에서 IT 컨설턴트 관련 채...",4.0,검색된 맥락 데이터가 질문에 부분적으로만 관련됨. 제공된 채용 공고는 울산에서 IT...,4.000000
27,정보보안 전문가 채용 공고 좀 보여줘,"근무지: 서울\n지역: 마포구\n직군: 정보보호\n직무: ['보안 엔지니어', '서...",현재 정보보안 전문가 채용 공고는 다음과 같습니다:\n\n1. **회사명**: 한국...,8.0,"답변이 검색된 맥락 데이터에 대부분 부합하며, 일부 세부사항은 직접 뒷받침되지만 약...",9.0,"생성된 답변은 질문에 잘対応하며, 필요한 정보를 거의 모두 포함하고 있습니다. 그러...",8.0,검색된 맥락 데이터가 질문에 매우 관련되며 대부분의 필요한 정보를 포함하고 있습니다...,8.333333
28,마케팅 직무를 채용하는 회사를 알려줘,회사명: 위버케어\n근무지: 서울\n지역: 강남구\n직군: 마케팅광고\n직무: ['...,현재 마케팅 직무를 채용하는 회사는 다음과 같습니다:\n\n1. **위버케어**\n...,10.0,"생성된 답변의 모든 내용이 검색된 맥락 데이터에서 직접 뒷받침됨. 회사명, 근무지,...",10.0,"생성된 답변이 질문에 완벽하게 답변하며, 모든 필요한 정보를 정확하고 완전하게 제공...",10.0,"검색된 맥락 데이터가 질문에 완벽하게 관련되고, 답변에 필요한 모든 정보를 포함하고...",10.000000
29,AI 직무를 채용하는 회사가 있을까?,회사명: 슈퍼브에이아이Superb AI\n근무지: 서울\n지역: 강남구\n직군: 경...,"네, AI 직무를 채용하는 회사가 여러 곳 있습니다. 예를 들어, '에이아이썸'이라...",9.0,"답변이 검색된 맥락 데이터에 대부분 부합하며, 에이아이썸의 회사 소개와 채용 요건이...",10.0,"답변이 질문에 완벽하게対応하며, 관련 회사와 그들의 AI 직무에 대한 상세한 정보를...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, 필요한 정보를 대부분 포함하고 있습니다...",9.333333
30,테스터가 되고 싶은데 ISTQB 자격증을 요구하는 회사를 알려줘,회사명: 화이트큐브\n근무지: 서울\n지역: 강남구\n직군: 개발\n직무: ['QA...,테스터 직무에 지원하기 위해 ISTQB 자격증을 요구하는 회사로는 '화이트큐브'가 ...,9.0,"답변이 검색된 맥락 데이터에 대부분 사실적으로 부합하며, ISTQB 자격증을 요구하...",9.0,"답변이 질문에 완벽하게対応하며, ISTQB 자격증을 요구하는 회사들에 대한 정확한 ...",9.0,"검색된 맥락 데이터가 질문에 매우 관련되며, ISTQB 자격증을 요구하는 회사 정보...",9.000000
31,프로덕트 매니저 채용 공고 좀 보여줘,게시글 ID: 276884\n제목: Product 프로덕트 매니저\n\n게시글 ID...,"프로덕트 매니저 채용 공고는 다양한 기업에서 자주 올라오며, 각 공고마다 요구하는 ...",6.0,"답변이 검색된 맥락 데이터의 일부를 반영하지만, 많은 내용이 맥락에서 직접 뒷받침되...",8.0,생성된 답변은 질문에 잘対応하여 프로덕트 매니저 채용 공고의 일반적인 내용을 포함하...,6.0,검색된 맥락 데이터는 프로덕트 매니저의 일반적인 역할과 자격 요건에 대해 언급했지만...,6.666667

In [54]:
results.to_json('rag_evaluation_results_Retriever_4.json', orient='records', force_ascii=False, indent=4)